from pydantic import BaseModel, Field
from typing import List, Optional, Literal

# Lesson Block Types
LessonBlockType = Literal[
    "Brain Warm-up",
    "Knowledge Activation",
    "Review Previous Material",
    "Introduction to Topic",
    "Main Topic Explanation",
    "Interactive Discussion",
    "Practical Exercise",
    "Group Activity",
    "Pair Work",
    "Independent Work",
    "Critical Thinking Exercise",
    "Creative Task",
    "Physical Activity Break",
    "Educational Game",
    "Quiz",
    "Reflection",
    "Question and Answer Session",
    "Summary",
    "Homework Explanation",
    "Feedback Session"
]

# Activity Suggestions Types
ActivityType = Literal[
    "Historical Roleplay",
    "Mini Quiz Competition",
    "Team Puzzle Challenge",
    "Educational Debate",
    "Treasure Hunt",
    "Ancient Civilization Storytelling",
    "Scientific Experiment",
    "Interactive Map Exploration",
    "Math Escape Room",
    "Creative Drawing Task",
    "Memory Card Game",
    "Word Association Game",
    "Simulation Activity",
    "Classroom Investigation",
    "Problem Solving Challenge",
    "Physical Movement Game",
    "Real Life Scenario Analysis",
    "Crossword Challenge",
    "Build and Explain Activity",
    "Timeline Construction"
]

class LessonBlock(BaseModel):
    title: str = Field(..., description="The type/title of the lesson block")
    durationMinutes: int = Field(..., description="Duration of this block in minutes")
    specific_topic: Optional[str] = Field(None, description="A detailed paragraph explaining the nuances of the topic for this block")
    specific_goals: Optional[str] = Field(None, description="A detailed paragraph explaining the pedagogical goals and how the teacher should achieve them")
    reference_links: List[str] = Field(default_factory=list, description="Referral links (URLs) to external sources used for this block data")
    description: str = Field(..., description="Detailed description of what happens in this block")
    detailed_content: Optional[str] = Field(None, description="The EXACT content to be used in class (e.g., exact teacher dialogue, texts for dictation, exact puzzles, specific rules). Provide the 'meat' of the lesson here.")

class Exercise(BaseModel):
    title: str = Field(..., description="Title or type of the exercise")
    problem_statement: str = Field(..., description="The exact problem, task, or question for the student to solve")
    solution_or_guidance: str = Field(..., description="The exact solution, answer key, or guidance for the teacher")

class QuizQuestion(BaseModel):
    question: str = Field(..., description="The exact quiz question")
    correct_answer: str = Field(..., description="The correct answer")

class HomeworkTask(BaseModel):
    title: str = Field(..., description="Title of the homework task")
    description: str = Field(..., description="Detailed instructions for the student")

class ActivitySuggestion(BaseModel):
    title: str = Field(..., description="Title of the suggested activity")
    description: str = Field(..., description="Detailed description of the activity")
    relatedTopic: str = Field(..., description="How this activity relates to the main topic")

class LocalizationLabels(BaseModel):
    lbl_duration: str = Field(..., description="Translation for 'Total Duration'")
    lbl_minutes: str = Field("min", description="Translation for 'minutes' or 'min'")
    lbl_objectives: str = Field(..., description="Translation for 'Learning Objectives'")
    lbl_structure: str = Field(..., description="Translation for 'Lesson Structure'")
    lbl_detailed_topic: str = Field(..., description="Translation for 'Detailed Topic:'")
    lbl_teaching_guidance: str = Field(..., description="Translation for 'Teaching Guidance & Goals:'")
    lbl_references: str = Field(..., description="Translation for 'References:'")
    lbl_exercises: str = Field(..., description="Translation for 'Classroom Exercises'")
    lbl_problem: str = Field(..., description="Translation for 'Problem:'")
    lbl_guidance: str = Field(..., description="Translation for 'Teacher\\'s Guidance:'")
    lbl_minitest: str = Field(..., description="Translation for 'Mini-Test / Quick Check'")
    lbl_question: str = Field(..., description="Translation for 'Question:'")
    lbl_answer: str = Field(..., description="Translation for 'Answer:'")
    lbl_homework: str = Field(..., description="Translation for 'Homework Assignments'")
    lbl_activities: str = Field(..., description="Translation for 'Activity Suggestions'")
    lbl_related_to: str = Field(..., description="Translation for 'Related to:'")
    lbl_summary: str = Field(..., description="Translation for 'Final Summary:'")
    lbl_footer: str = Field("Generated by AI Lesson Planning Platform", description="Translation for 'Generated by AI Lesson Planning Platform'")

class LessonPlanResponse(BaseModel):
    topic: str = Field(..., description="The main topic of the lesson")
    localization: LocalizationLabels = Field(..., description="Translated labels for the UI/PDF matching the language of the lesson")
    learningObjectives: List[str] = Field(..., description="List of specific learning objectives or competencies for the students")
    totalDuration: int = Field(..., description="Total duration of the lesson in minutes")
    lessonBlocks: List[LessonBlock] = Field(..., description="List of sequential lesson segments")
    exercises: List[Exercise] = Field(default_factory=list, description="List of specific classroom exercises or problems")
    miniTest: List[QuizQuestion] = Field(default_factory=list, description="A quick check or mini-test to assess understanding")
    homework: List[HomeworkTask] = Field(..., description="List of homework assignments")
    activitySuggestions: List[ActivitySuggestion] = Field(..., description="List of interactive activity ideas")
    summary: str = Field(..., description="A brief summary of the entire lesson plan")
